package com.example.mycity.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xff1760a5)
val light_on_primary = Color(0xffffffff)
val light_primary_container = Color(0xffd3e3ff)
val light_on_primary_container = Color(0xff001c39)
val light_secondary = Color(0xff545f70)
val light_on_secondary = Color(0xffffffff)
val light_secondary_container = Color(0xffd8e3f8)
val light_on_secondary_container = Color(0xff111c2b)
val light_tertiary = Color(0xff6d5677)
val light_on_tertiary = Color(0xffffffff)
val light_tertiary_container = Color(0xfff5d9ff)
val light_on_tertiary_container = Color(0xff261430)
val light_error = Color(0xffba1a1a)
val light_on_error = Color(0xffffffff)
val light_error_container = Color(0xffffdad6)
val light_on_error_container = Color(0xffC410002)
val light_background = Color(0xfffdfcff)
val light_on_background = Color(0xff1a1c1e)
val light_surface = Color(0xfffdfcff)
val light_on_surface= Color(0xff1a1c1e)
val light_outline = Color(0xff73777f)
val light_surface_variant = Color(0xffdfe2eb)
val light_on_surface_variant = Color(0xff43474e)

val dark_primary = Color(0xffa3c9ff)
val dark_on_primary = Color(0xff00315c)
val dark_primary_container = Color(0xff004882)
val dark_on_primary_container = Color(0xffd3e3ff)
val dark_secondary = Color(0xffbcc7db)
val dark_on_secondary = Color(0xff263141)
val dark_secondary_container = Color(0xff3c4758)
val dark_on_secondary_container = Color(0xffd8e3f8)
val dark_tertiary = Color(0xffd9bde3)
val dark_on_tertiary = Color(0xff3c2947)
val dark_tertiary_container = Color(0xff543f5e)
val dark_on_tertiary_container = Color(0xfff5d9ff)
val dark_error = Color(0xffffb4ab)
val dark_on_error = Color(0xff690005)
val dark_error_container = Color(0xff93000a)
val dark_on_error_container = Color(0xffffdad6)
val dark_background = Color(0xff1a1c1e)
val dark_on_background = Color(0xffe3e2e6)
val dark_surface = Color(0xff1a1c1e)
val dark_on_surface= Color(0xffe3e2e6)
val dark_outline = Color(0xff8d9199)
val dark_surface_variant = Color(0xff43474e)
val dark_on_surface_variant = Color(0xffc3c6cf)